### ISSUE TITLE
F4 Menu VCMiner Cooler Bugged

### ISSUE THREAD

**Issue by HugestFella23** [civilnetworks-projects/DarkRP_Public_Development#22]
**Title of the Bug**
F4 Menu VCMiner Cooler Bugged

**Description**
The VCMiner Cooler in the F4 menu does not work when spawned. Additionally it is more expensive than buying it from VCMiner.com.

**Steps to Reproduce**
(Your goto way to recreate this bug.)
1. Open F4 menu and find VCMiner cooler.
2. Spawn it in, it will spawn the entity
3. The entity will be immovable, and will not connect to a vcminer.
4. Requires superadmin perms in order to delete

**Expected Behavior**
A working cooler will spawn, which can be used the same as coolers from the VCMiner website.

**Actual Behavior**
The entity will be immovable, and will not connect to a vcminer.

**Evidence**
(If possible, please put any screenshots or videos)

**Comment by cloakical** [comment]
Tried something else to fix this after restart, will see if it works

**Comment by cloakical** [comment]
Fixed now although they can't be gravgunned/physgunned yet, but this is a much lower priority bug, as they can at least be connected to miners now. They should be at least gravgunnable after next restart also

**Comment by HugestFella23** [comment]
Players are still having issues with the F4 coolers, they still don't seem to be working at all.
https://imgur.com/a/w1Kd3Rg

**Comment by cloakical** [comment]
have you tried gravgunning the miner into the cooler, I have tried that and it works fine.

**Comment by HugestFella23** [comment]
I'm not able to gravgun or physgun the coolers, they also won't attach to miners, as I tried this earlier and it didn't work.
https://imgur.com/a/hJjdPai

**Comment by relz999** [comment]
I've found a fix, which is to add owning_ent networkvar to the shared.lua of the cooler, the cooler entity does not have a base entity which is setting this networkvar for other items. I've made a pull request on github and once approved I will push the fix to the live server.
